### ISSUE TITLE
Gerber format ?

### ISSUE THREAD

**Issue by wrbst** [stacksmashing/jwst_christmas_ornament_pcb#1]
Hello,
Can you upload the project in Gerber format as well?

Thank you.

**Comment by nezza** [comment]
Added gerbers with the default settings!

Cheers!
<img width="840" alt="Screenshot 2022-12-22 at 12 48 06" src="https://user-images.githubusercontent.com/208596/209128151-0d782982-6ee2-4b37-8734-4ee98c890048.png">
